### ISSUE TITLE
1.19.2 version

### ISSUE THREAD

**Issue by Abbie5** [mysticdrew/FabricScreenLayers#2]
I've ported the mod to 1.19.2 on my own [branch](https://github.com/Abbie5/FabricScreenLayers/tree/1.19.2), feel free to use that if you like.

**Comment by mysticdrew** [comment]
Odd, I am supposed to get emails when issues are created. I'm sorry, I just noticed you did this. I can create a branch if you want to create a PR

**Comment by mysticdrew** [comment]
I was able to do it on my end. I will publish a release to our maven and cf/md

Thanks
